# Generated by Django 2.2.3 on 2019-07-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('booking_type', models.CharField(max_length=120, verbose_name='booking_type')),
                ('startdate', models.DateTimeField(verbose_name='startdate')),
                ('enddate', models.DateTimeField(verbose_name='enddate')),
                ('reason', models.CharField(max_length=120, verbose_name='reason')),
                ('status', models.CharField(max_length=120, verbose_name='status')),
                ('destination', models.CharField(max_length=120, verbose_name='destination')),
                ('pickup', models.CharField(max_length=120, verbose_name='pickup')),
            ],
        ),
    ]
