# Generated by Django 2.0.7 on 2019-07-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_booking_booking_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('Onstation', 'Onstation'), ('Outstation', 'Outstation')], default='null', max_length=120, verbose_name='booking_type'),
        ),
    ]
