# Generated by Django 2.0.7 on 2019-07-27 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190726_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingType',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_type',
        ),
    ]
