# Generated by Django 2.2.3 on 2019-07-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190727_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Booking', 'Booking'), ('Returned', 'Returned')], max_length=120, verbose_name='status'),
        ),
    ]
